version: 1
region: us-east-1
handler: "src/index.handler"
memory: 512
timeout: 60

stacks:
  - stack: "dev"
    environment:
      - PROFILE_ACTIVE: "dev"
      - CITY_TABLE: "sbc-autodamage-dev-user-dynamodb"
  - stack: "stg"
    environment:
      - PROFILE_ACTIVE: "stg"
      - CITY_TABLE: "sbc-autodamage-stg-user-dynamodb"
  - stack: "pro"
    environment:
      - PROFILE_ACTIVE: "pro"
      - CITY_TABLE: "sbc-autodamage-pro-user-dynamodb"