version: "1"

region: "us-east-1" # AWS Region where the lambda run

apiGW: # If you are using AWS API Gateway
stage: "stg" # Stage where you can publish the AWS API Gateway config paths

lambdas:
        - FunctionName: 'JuanFelipePruebas' # [REQUIRED] The name of the Lambda function.
          MemorySize: 256
          Environment: # Environment variables that are accessible from function code during execution
            Variables:  # Environment variable key-value pairs.
              clave1: 'valor1actualizadoGithub'
              clave2: 'valor2actualizado1Github'

        - FunctionName: 'JuanFelipePruebas2' # [REQUIRED] The name of the Lambda function.
          Environment: # Environment variables that are accessible from function code during execution
            Variables:  # Environment variable key-value pairs.
              clave1: 'valorunoactualizado2Github'
              clave2: 'valordosactualizado2Github'