version: "1"

region: "us-east-1" # AWS Region where the lambda run

apiGW: # If you are using AWS API Gateway
stage: "pro" # Stage where you can publish the AWS API Gateway config paths

lambdas:

        - FunctionName: 'JuanFelipePruebas' # [REQUIRED] The name of the Lambda function.
          dev:
                  Environment:
                          Variables:

                                  clave1: 'valor1DevPruebas1Github'
                                  clave2: 'valor2DevPruebas1Github'
          stg:
                  Environment:
                          Variables:

                                  clave1: 'valor1StgPruebas1Github'
                                  clave2: 'valor2StgPruebas1Github'
          pro:
                  Environment:
                          Variables:

                                  clave1: 'valor1ProPruebas1Github'
                                  clave2: 'valor2ProPruebas1Github'                        

        - FunctionName: 'JuanFelipePruebas2' # [REQUIRED] The name of the Lambda function.
          dev:
                  Environment:
                          Variables:

                                  clave1: 'valor1DevPruebas2Github'
                                  clave2: 'valor2DevPruebas2Github'
          stg:
                  Environment:
                          Variables:

                                  clave1: 'valor1StgPruebas2Github'
                                  clave2: 'valor2StgPruebas2Github'
          pro:
                  Environment:
                          Variables:

                                  clave1: 'valor1ProPruebas2Github'
                                  clave2: 'valor2ProPruebas2Github'
