name: Deploy to Develop
on:
  pull_request:
    branches: [develop]
    types: [closed]

env:
  PREFIJO: sbc-autodamage-dev
  POSTFIJO: lambda
  BUCKET: sbc-autodamage-dev-build-lambdas-bucket
  REGION: us-east-1
    
jobs:
    deploy:
        name: "Deploy"
        if: ${{ github.event.pull_request.merged }}
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOP }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOP }}
            REGION: ${{ secrets.REGION_DEVELOP }}
 
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: Setup Python
            uses: actions/setup-python@v2

          - name: Update Python AWS Cli
            run:  python3 -m pip install --user awscli

          - name: Package Lambdas
            run:  |
                for dir in */; do
                  echo "----"
                  echo "$dir"
                  cd $dir
                  mkdir -p "$PREFIJO-${dir%?}-deploy-$POSTFIJO"
                  cd src
                  pip install -r ../config/requirements.txt -t ../"$PREFIJO-${dir%?}-$POSTFIJO"
                  cd ..
                  cp -r src/* "$PREFIJO-${dir%?}-$POSTFIJO"
                  cd "$PREFIJO-${dir%?}-$POSTFIJO"
                  zip -r ../"$PREFIJO-${dir%?}-$POSTFIJO.zip" .
                  cd ..
                done

          - name: Upload Lambdas
            run:  |
              for dir in */; do
                echo "----"
                echo "$dir"
                cd $dir
                aws s3 --region us-east-1 cp "$PREFIJO-${dir%?}-$POSTFIJO.zip" s3://$BUCKET
              done

          - name: Deploy Lambdas
            run:  |
              for dir in */; do
                echo "----"
                echo "$dir"
                aws lambda update-function-code \
                  --region $REGION  \
                  --function-name "$PREFIJO-${dir%?}-lambda" \
                  --s3-bucket $BUCKET \
                  --s3-key "$PREFIJO-${dir%?}-$POSTFIJO.zip"
              done

          # - name: Update Configuration Lambda
          #   run:  |
          #       for dir in */; do
          #         echo "----"
          #         echo "$dir"
          #         cd $dir
          #         aws lambda update-function-configuration \
          #           --region "us-east-1" \
          #           --function-name "sbc-autodamage-dev-${dir%?}-lambda" \
          #           --environment Variables="{VAR1=variable_value, VAR2=variable_value}"
          #       done
  
  
               
  
    
              

