name: CheckPlan to Develop
on:
  pull_request:
    branches: [develop]

env:
  PREFIJO: sbc-pruebas-dev
  POSTFIJO: deploy-lambda
  BUCKET: bucket-pruebas-juanfelipe
  LAMDAFUNCTION: JuanFelipePruebas
  REGION: us-east-1

jobs:
    deploy:
        name: "CheckPlan"
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOP }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOP }}
            #REGION: ${{ secrets.REGION_DEVELOP }}
 
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: Setup Python
            uses: actions/setup-python@v2

          - name: Update Python AWS Cli
            run:  python3 -m pip install --user awscli

          - name: Package Lambdas
            id: Package_Lambdas
            run:  |
                  for dir in */; do
                    echo "----"
                    echo "$dir"
                    cd $dir
                    mkdir -p "$PREFIJO-${dir%?}-$POSTFIJO"
                    cd src
                    pip install -r ../config/requirements.txt -t ../"$PREFIJO-${dir%?}-$POSTFIJO"
                    cd ..
                    cp -r src/* "$PREFIJO-${dir%?}-$POSTFIJO"
                    cd "$PREFIJO-${dir%?}-$POSTFIJO"
                    zip -r ../"$PREFIJO-${dir%?}-$POSTFIJO.zip" .
                    cd ..
                  done
                  
          - name: Upload Lambdas
            id: Upload_Lambdas
            run:  |
                for dir in */; do
                  echo "----"
                  echo "$dir"
                  cd $dir
                  aws s3 --region $REGION cp "$PREFIJO-${dir%?}-$POSTFIJO.zip" s3://$BUCKET
                done

          - name: Update Lambda
            id: Update_lambda
            run: |
                echo "$PREFIJO-${dir%?}-$POSTFIJO.zip"
                aws lambda update-function-code --region $REGION --function-name $LAMDAFUNCTION --s3-bucket $BUCKET --s3-key "$PREFIJO-${dir%?}-$POSTFIJO.zip"

