name: CheckPlan to Develop
on:
  pull_request:
    branches: [develop]

env:
  PREFIJO: sbc-pruebas-dev
  POSTFIJO: deploy-lambda
  BUCKET: bucket-pruebas-juanfelipe
  LAMDAFUNCTION: JuanFelipePruebas
  REGION: us-east-1

jobs:
    deploy:
        name: "CheckPlan"
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEVELOP }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOP }}
            #REGION: ${{ secrets.REGION_DEVELOP }}
 
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: Setup Python
            uses: actions/setup-python@v2

          - name: Update Python AWS Cli
            run:  python3 -m pip install --user awscli

          - name: Package Lambdas to zip
            id: Package_Lambdas
            run:  |
                  for dir in */; do
                    echo "----"
                    echo "$dir"
                    cd $dir
                    mkdir -p "$PREFIJO-${dir%?}-$POSTFIJO"
                    cd src
                    pip install -r ../config/requirements.txt -t ../"$PREFIJO-${dir%?}-$POSTFIJO"
                    cd ..
                    cp -r src/* "$PREFIJO-${dir%?}-$POSTFIJO"
                    cd "$PREFIJO-${dir%?}-$POSTFIJO"
                    zip -r ../"$PREFIJO-${dir%?}-$POSTFIJO.zip" .
                    cd ..
                  done
                  
          - name: Upload Lambdas to S3
            id: Upload_Lambdas_to_S3
            run:  |
                for dir in */; do
                  echo "----"
                  echo "$dir"
                  cd $dir
                  aws s3 --region $REGION cp "$PREFIJO-${dir%?}-$POSTFIJO.zip" s3://$BUCKET
                done

          - name: Update Lambda Code from S3
            id: Update_lambda_code_from_S3
            run: |                
                for dir in */; do                
                  aws lambda update-function-code --region $REGION --function-name $LAMDAFUNCTION --s3-bucket $BUCKET --s3-key "$PREFIJO-${dir%?}-$POSTFIJO.zip"
                  sleep 10s
                done
                

          - name: Update Lambda Configuration
            id: Update_lambda_configuration
            run: |                                
                for dir in */; do
                cd $dir 
                  cat config/configlambda.txt | while read -r line; do
                    if [ -n "$line" ]; then
                      aws lambda update-function-configuration --region $REGION --function-name JuanFelipePruebas $line
                    fi
                  done
                done

